version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: quizzo_user
      POSTGRES_PASSWORD: quizzo_pass
      POSTGRES_DB: quizzo_db
    ports:
      - "5433:5432"
    logging:
      driver: "none"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: "5000"
      # Use the database running in the 'db' service
      DATABASE_URL: "postgresql://quizzo_user:quizzo_pass@db:5432/quizzo_db?schema=public"
    # volumes:
    #   - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: "3000"
      # Override the backend URL so that the Next.js app can connect to the backend container
      NEXT_PUBLIC_BACKEND_URL: "http://backend:5000"
    # volumes:
      # - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data:
